# Generated by Django 4.1 on 2024-01-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
